version: '3.9'
name: sonarqube

services:
  sonarqube-server:
    image: sonarqube:community
    container_name: server
    ports:
      - "9000:9000"
    networks:
      - sonar
    restart: on-failure:3
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

networks:
  sonar:
    name: sonar

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarqube_bundled-plugins: